"""empty message

Revision ID: 3fe6b8444d34
Revises: 
Create Date: 2020-06-11 17:00:49.618605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe6b8444d34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('lastname', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('petition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=10), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('change_or_return', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boughtproduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('petition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['petition_id'], ['petition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_product', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('commune', sa.String(length=50), nullable=True),
    sa.Column('petition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['petition_id'], ['petition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.Integer(), nullable=True),
    sa.Column('petition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['petition_id'], ['petition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardNumber', sa.Integer(), nullable=False),
    sa.Column('cvv', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrepreneur_name', sa.String(length=10), nullable=False),
    sa.Column('entrepreneur_lastname', sa.String(length=10), nullable=False),
    sa.Column('entrepreneur_email', sa.String(length=10), nullable=False),
    sa.Column('client_name', sa.String(length=10), nullable=False),
    sa.Column('client_lastname', sa.String(length=10), nullable=False),
    sa.Column('client_email', sa.String(length=10), nullable=False),
    sa.Column('booked_date', sa.DateTime(), nullable=False),
    sa.Column('city', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('courrier', sa.String(length=10), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('number_of_packages', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.Integer(), nullable=False),
    sa.Column('postCode', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('billing_details')
    op.drop_table('user')
    op.drop_table('return')
    op.drop_table('change')
    op.drop_table('boughtproduct')
    op.drop_table('petition')
    op.drop_table('person')
    # ### end Alembic commands ###
