"""empty message

Revision ID: 7af038a2c79a
Revises: 
Create Date: 2020-07-15 13:53:37.834676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af038a2c79a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardNumber', sa.Integer(), nullable=False),
    sa.Column('cvv', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_password', sa.String(length=150), nullable=False),
    sa.Column('employee_email', sa.String(length=150), nullable=False),
    sa.Column('employee_firstName', sa.String(length=150), nullable=False),
    sa.Column('employee_lastName', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=50), nullable=False),
    sa.Column('streetAddress', sa.String(length=50), nullable=False),
    sa.Column('commune', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('products', sa.String(length=50), nullable=False),
    sa.Column('courrier', sa.String(length=50), nullable=False),
    sa.Column('client_email', sa.String(length=50), nullable=False),
    sa.Column('cellphone', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('petition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=10), nullable=False),
    sa.Column('asked_number', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('change_or_return', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sender_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storeName', sa.String(length=20), nullable=False),
    sa.Column('contactName', sa.String(length=20), nullable=False),
    sa.Column('companyName', sa.String(length=20), nullable=False),
    sa.Column('contactPhone', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('emailContact', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('firstname', sa.String(length=150), nullable=False),
    sa.Column('lastname', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('boughtproduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('petition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['petition_id'], ['petition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_product', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('commune', sa.String(length=50), nullable=True),
    sa.Column('petition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['petition_id'], ['petition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.Integer(), nullable=True),
    sa.Column('petition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['petition_id'], ['petition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('return')
    op.drop_table('change')
    op.drop_table('boughtproduct')
    op.drop_table('user')
    op.drop_table('sender_details')
    op.drop_table('petition')
    op.drop_table('order')
    op.drop_table('employee')
    op.drop_table('billing_details')
    # ### end Alembic commands ###
