"""empty message

Revision ID: 8c92a35b7f16
Revises: 37bd9cb54051
Create Date: 2020-07-10 22:42:05.300394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c92a35b7f16'
down_revision = '37bd9cb54051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sender_details', sa.Column('address', sa.String(length=20), nullable=False))
    op.add_column('sender_details', sa.Column('city', sa.String(length=30), nullable=False))
    op.add_column('sender_details', sa.Column('contactPhone', sa.Integer(), nullable=False))
    op.add_column('sender_details', sa.Column('industry', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sender_details', 'industry')
    op.drop_column('sender_details', 'contactPhone')
    op.drop_column('sender_details', 'city')
    op.drop_column('sender_details', 'address')
    # ### end Alembic commands ###
