"""empty message

Revision ID: 9d8de72b8e8f
Revises: 0b6f0c71e0e9
Create Date: 2020-07-07 19:05:34.672150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8de72b8e8f'
down_revision = '0b6f0c71e0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirm_order')
    op.add_column('order', sa.Column('user_email', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'order', 'user', ['user_email'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'user_email')
    op.create_table('confirm_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('streetAddress', sa.VARCHAR(length=50), nullable=False),
    sa.Column('commune', sa.VARCHAR(length=50), nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=False),
    sa.Column('office_id', sa.INTEGER(), nullable=False),
    sa.Column('products', sa.VARCHAR(length=50), nullable=False),
    sa.Column('courrier', sa.VARCHAR(length=50), nullable=False),
    sa.Column('client_email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('cellphone', sa.INTEGER(), nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
